### ISSUE TITLE
recursivelyGarbageCollect error

### ISSUE THREAD

**Issue by valmiRe** [asyncly/EventEmitter2#187]
trying to upgrade from v0.4.14 to v1 or v2, I got the error below. 
The code raising the error just adds a new listener after removing some others by calling the removeAllListeners method multiple times. 
There is no error if I comment the removeAllListeners part in my code.

```
/[***]/node_modules/eventemitter2/lib/eventemitter2.js:623
        if (Object.keys(obj).length > 0) {
                   ^
TypeError: Cannot convert undefined or null to object
    at recursivelyGarbageCollect (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:623:20)
    at recursivelyGarbageCollect (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:624:11)
    at recursivelyGarbageCollect (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:624:11)
    at recursivelyGarbageCollect (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:624:11)
    at EventEmitter.off (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:631:5)
    at EventEmitter.listener (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:252:14)
    at EventEmitter.emit (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:348:22)
    at EventEmitter.end (/[***]/modules/hook.js:253:27)
    at EventEmitter.emit (/[***]/node_modules/eventemitter2/lib/eventemitter2.js:348:22)
    at end (/[***]/modules/deploy.js:396:31)
```

**Comment by RangerMauve** [comment]
Oh weird. I'm a bit busy this week, but a PR with a unit test would be appreciated. All that needs to be added is a check to make sure that `obj` isn't falsy [on this line](https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L621) in addition to the other checks.

The unit test should just have the minimal code used to reproduce this issue. (I'm guessing a call to `removeAllListeners` in the same way you did it would be enough)

**Comment by valmiRe** [comment]
sorry but I won't be able to write the unit test
My first description was incomplete, you need to emit an event which will be receive by a *once* listener, just after removing another listener. Also the *wildcard* option must be set

here is a sample code to reproduce the issue :

```
var EventEmitter2 = require('eventemitter2').EventEmitter2;
var eventemitter = new EventEmitter2({ wildcard: true });

eventemitter.on('test1', function(data) { console.log(data); });
eventemitter.once('test2', function(data) { console.log(data); });

eventemitter.emit('test1','test1');
eventemitter.removeAllListeners('test1');
eventemitter.emit('test2','test2');
```

**Comment by RangerMauve** [comment]
Hopefully I'll have time sooner than later to fix it up, then. :D Thanks for reporting it!
