### ISSUE TITLE
The performance tests are broken.

### ISSUE THREAD

**Issue by agirorn** [asyncly/EventEmitter2#229]
When I run the performance tests it fails.

```shell
EventEmitter2 git:(master) ✗ ./node_modules/.bin/nodeunit test/perf/benchmark.js 
EventEmitterHeatUp x 4,246,065 ops/sec ±0.28% (94 runs sampled)
EventEmitter x 4,099,899 ops/sec ±1.57% (92 runs sampled)
EventEmitter2 x 14,586,093 ops/sec ±1.01% (93 runs sampled)
EventEmitter2 (wild) x 11,040,898 ops/sec ±0.74% (89 runs sampled)

/home/agirorn/code-open/EventEmitter2/test/perf/benchmark.js:50
    console.log('\nFastest is ' + this.filter('fastest').pluck('name'));
                                                         ^
TypeError: this.filter(...).pluck is not a function
    at Suite.<anonymous> (/home/agirorn/code-open/EventEmitter2/test/perf/benchmark.js:50:58)
    at /home/agirorn/code-open/EventEmitter2/node_modules/benchmark/benchmark.js:1215:40
    at arrayEach (/home/agirorn/code-open/EventEmitter2/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/agirorn/code-open/EventEmitter2/node_modules/lodash/lodash.js:9359:14)
    at Suite.emit (/home/agirorn/code-open/EventEmitter2/node_modules/benchmark/benchmark.js:1214:11)
    at Suite.onComplete (/home/agirorn/code-open/EventEmitter2/node_modules/benchmark/benchmark.js:1186:17)
    at getNext (/home/agirorn/code-open/EventEmitter2/node_modules/benchmark/benchmark.js:900:30)
    at execute (/home/agirorn/code-open/EventEmitter2/node_modules/benchmark/benchmark.js:862:26)
    at invoke (/home/agirorn/code-open/EventEmitter2/node_modules/benchmark/benchmark.js:970:20)
    at Suite.runSuite [as run] (/home/agirorn/code-open/EventEmitter2/node_modules/benchmark/benchmark.js:1169:7)
    at Object.<anonymous> (/home/agirorn/code-open/EventEmitter2/test/perf/benchmark.js:53:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by RangerMauve** [comment]
I haven't had much time to do maintenance, and this looks like a library version problem. A pr to fix this would be very much appreciated!

**Comment by evilive3000** [comment]
just replace `pluck` with `map`

before:
`this.filter('fastest').pluck('name')`
after:
`this.filter('fastest').map('name')`

**Comment by RangerMauve** [comment]
@evilive3000 Would you mind testing it out and submitting a PR?
